### ISSUE TITLE
Make the project a PWA

### ISSUE THREAD

**Issue by deniszholob** [deniszholob/factorio-cheat-sheet#102]
* Add manifest
* Add Service worker
* Generate icons https://app-manifest.firebaseapp.com/

**Comment by dalanmiller** [comment]
This PR just needs some conflict resolution and will be shippable again - https://github.com/deniszholob/factorio-cheat-sheet/pull/86

**Comment by deniszholob** [comment]
Hey @dalanmiller  i was actually looking at a better integration with angular.
I tried to use the ngsw, but that while worked on the vanilla ng generated project somehow was unreliable in offline mode when i added more content.
I am looking into this option with workbox now.
https://golb.hplar.ch/2018/06/workbox-serviceworker-in-angular-project.html
