### ISSUE TITLE
Remove link to Reddit thread, reddit has archived the thread.

### ISSUE THREAD

**Issue by HonkingGoose** [deniszholob/factorio-cheat-sheet#105]
Quote from Cheat Sheet:
> Please report any errors/suggestions on Github, Discord, or Reddit. 

**Problem:**
Reddit has archived the thread (https://www.reddit.com/r/factorio/comments/761o4u/the_factorio_cheat_sheet_v015/), so no new errors/suggestions can be posted there. This link has no more use now.

**Comment by deniszholob** [comment]
Good point, i think what ill do is when i have all the 0.17 data changed, create a new reddit post and lint it there, so we can all verify the correctness of the new information
