### ISSUE TITLE
Lazy load images that are offscreen

### ISSUE THREAD

**Issue by deniszholob** [deniszholob/factorio-cheat-sheet#110]
Only load images that are visible to improve performance.

Reference:
https://www.npmjs.com/package/ng-lazyload-image
https://www.talkingdotnet.com/how-to-lazy-load-images-angular-6/
https://github.com/TradeMe/ng-defer-load

**Comment by wormeyman** [comment]
what about just adding loading="lazy" to all the images? https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading

**Comment by deniszholob** [comment]
Looks like a nice and simple solution
I havent had the time allocation to really research this ticket, but your solution seems nice and simple.
i know i had a branch using ng-lazyload-image but i dont recall why i didnt proceed to merge it
https://github.com/deniszholob/factorio-cheat-sheet/pull/173/
