### ISSUE TITLE
Update Solid Fuel Production for 0.17

### ISSUE THREAD

**Issue by HonkingGoose** [deniszholob/factorio-cheat-sheet#121]
The ratios mentioned might be off, the Factorio wiki says:
>Solid fuel production is best done using light oil because it has the best oil to fuel ration (10:1). 

Source: https://wiki.factorio.com/Tutorial:Cheat_sheet#Oil_refining

Beware, this page **has not been updated to 0.17 yet on the wiki!**:
https://wiki.factorio.com/Solid_fuel#Which_solid_fuel_recipe_to_use

**Comment by deniszholob** [comment]
Double checked the ratios with in game tooltips, seems to be still the same.
Re-open if im wrong
