### ISSUE TITLE
Update Inserter throughput section

### ISSUE THREAD

**Issue by deniszholob** [deniszholob/factorio-cheat-sheet#139]
Use https://docs.google.com/spreadsheets/d/1XAPlznJXXAILzjsvj9jE7ltI8roRkxp4nSZzsDJcASY/edit#gid=0
and https://wiki.factorio.com/Tutorial:Cheat_sheet for reference
PR can be crated against the master branch now

**Comment by Bilka2** [comment]
Updated and more complete numbers can be found on https://docs.google.com/spreadsheets/d/1Q4hxL69qrK3qeEKU8aDkuwM3gJy6I2dJ4FYSs-FQUpI/edit?usp=sharing and https://wiki.factorio.com/Inserters
