### ISSUE TITLE
Bugfixing for 0.17 release

### ISSUE THREAD

**Issue by deniszholob** [deniszholob/factorio-cheat-sheet#140]
* Use d-lg-table-cell instead of d-lg-block (nuclear table)
* "train speed" in the side panel broken
* Wrong info: Any item with a “fuel value” in its description can be used as fuel (including wooden chests & wooden power poles). => Wooden chests and wooden power poles can not be burned anymore. (And the tooltip will now explicitly say "can be used as a fuel source" or something similar.
* Numbers for centrifuges to empty an ore belt: The wiki now says crafting speed was increased from 0.75 to 1, but the ore Uranium processing recipe was also changed from 10 seconds to 12. seems you now need exactly 54 to empty a new blue belt. @s3bash seems your spreadsheet does indeed say 10 :)
* Check common ratio science 5-10 military, 7->14 yellow
* "a Blue belt is exactly three times as fast a Yellow belt"
* Common ratio say brick 12.5/s

**Comment by s3bash** [comment]
Confirmed in game that centrifuges take 12 seconds for uranium processing. Will update the numbers. The Wiki still says 10 seconds, which is where I checked last time.

**Comment by s3bash** [comment]
It might be more useful to have each of issues found as separate issues instead of all in one. It would be cleaner to fix and close rather than have to come here and figure out what is done and what isn't. 
Or open an issue for each bullet point and add the link to it in here.

**Comment by deniszholob** [comment]
Yeah i created a couple from this that were more involved but fixed the rest of the simple tweaks
