### ISSUE TITLE
Basic oil strategy change for 017

### ISSUE THREAD

**Issue by deniszholob** [deniszholob/factorio-cheat-sheet#144]
Oil processing says, that one should rush advanced oil processing and that the heavy&light oil should be converted into flamethrower ammo. => Not a valid tactic in 0.17 anymore as you need plastic as well as solid fuel from the oil processing to craft the blue science packs.

Further research needed as to what a good replacement is in terms or ratios.
Thinking something like a couple refineries a plastic chem plant, a lube one and some solid fuels

**Comment by s3bash** [comment]
Finally finished (launched the first rocket) in 0.17 recently. I rushed to advanced oil, hand carried the items for the science packs. 

My oil strategy is to build the perfect ratio for advanced oil processing: 10:1:7 but with an extra chemical plant to turn heavy into lube placed before the heavy to light, light to petrol as normal, and then chemical plants below to turn any extra light to solid fuel, once plastic is up that will eat up the petrol but if there's any left over I have petrol to solid fuel going as well.

just my $0.02.

**Comment by HonkingGoose** [comment]
It seems the numbers are changing sometime after FFF#305:

From [FFF#305](https://factorio.com/blog/post/fff-305):

>We made slight changes to the numbers in the recipes - specifically, Basic oil processing results in a bit more Petroleum gas (45 instead of 40), and Advanced oil processing results in more Heavy oil (25 instead of 10) than before. This is because it was common to use Basic oil processing over Advanced oil processing when you needed a lot of lubricant for Express transport belts.

**Comment by deniszholob** [comment]
No longer relevant after 0.17.60 update, closing.
