### ISSUE TITLE
Enemy, Turret and Weapon Ranges

### ISSUE THREAD

**Issue by muppet9010** [deniszholob/factorio-cheat-sheet#148]
It would be useful to have the range data like this included:
https://i.redd.it/6kspraomuij21.png

**Comment by deniszholob** [comment]
What reddit post is this image from?

**Comment by muppet9010** [comment]
Or even just same info but shown in a more squashed way. I.e. each thing at the range it has down the ruler?

**Comment by josephspengler** [comment]
I reimagined the graphic in a more squashed method you might be interested in:
https://www.reddit.com/r/factorio/comments/bjbcsi/ranges_of_all_turrets_worms_vehicles_weapons_and/?

**Comment by deniszholob** [comment]
@josephspengler I def like the compactness, but it was not immediately clear to me, compared to the original, took me a bit of looking and reading your post. Maybe as you mentioned, labeling would help. IDK, ill think about it more later. Overall looks good though, thanks!

**Comment by josephspengler** [comment]
in the thread, danatron created a version with the labels:
https://i.imgur.com/6EenAcn.png

**Comment by deniszholob** [comment]
Created a new "Combat" Sheet and added the last image there. :D
Thanks to all that contributed!
