### ISSUE TITLE
Nuke, Fluid Wagon, Balancer Tweaks

### ISSUE THREAD

**Issue by deniszholob** [deniszholob/factorio-cheat-sheet#152]
* Nuke Common ratio 4 4 84 to make it more even.
"the second pictogram should be 4 nuclear, 4 pumps, 48 HE, 84 turbines. Because offshore pumps provide exactly 120 MW worth of water. Because you can't share pumps it needs to be rounded up to 84" - Mike C
* Fluid wagon transfer speed: mark as fastest theoretical (not experimental data)
* Maybe add some/change clarification images for the balances? (dont really want to add more, maybe combine the 1 lane balancer image with the 3 combinations, needs some thought)
"The lane balancer section could also use images of the other 2 types, plus the 2 or 3 lane swapping techniques." - Mike C
![](https://cdn.discordapp.com/attachments/552233145911738379/552236067760111627/BSKDWe6l.png)

**Comment by deniszholob** [comment]
Instead of a 2x lane balancer im thinking of adding a bus split off image and note
https://wiki.factorio.com/Tutorial:Main_bus#Split-off

**Comment by Bilka2** [comment]
We have updated experimental data on fluid wagon transfer on the wiki: https://wiki.factorio.com/Fluid_wagon. Note that the speed is much lower than in 0.16, so you should use empirical instead of theoretical numbers.

**Comment by deniszholob** [comment]
Updated the data to use the experimental results now, thanks!
