### ISSUE TITLE
Add tip about large screenshots

### ISSUE THREAD

**Issue by deniszholob** [deniszholob/factorio-cheat-sheet#155]
* https://www.reddit.com/r/factorio/comments/6f1gr6/psa_how_to_take_massive_screenshots/
* add tip about clearing the toolbar with MMB

**Comment by Bilka2** [comment]
Add tip about `/screenshot [x resolution] [y resolution] [zoom]  instead` - doesn't disable achieves, has GUI disabled by default.

**Comment by deniszholob** [comment]
Thanks Bilka!
