### ISSUE TITLE
Rocket component ratio is wrong

### ISSUE THREAD

**Issue by ElvishJerricco** [deniszholob/factorio-cheat-sheet#157]
This must have changed in 0.17. The rocket components ratio section says:

> This is a ratio of 1100:1050:1000 or simplified of 22:21:20 (divide by 50). As these components all have the same crafting time, this ratio applies.

However, the low density structures have a crafting time of 20, while rocket fuel and rocket control units each have a crafting time of 30.

**Comment by ElvishJerricco** [comment]
I believe that the ratio should be `(1100 * 20) : (1050 * 30) : (1000 * 30) = 44 : 63 : 60`. A convenient rounding being `45:60:60 = 2:3:3`.

**Comment by deniszholob** [comment]
Thanks for creating the issue, i was tracking it as part of #94 
The whole rocket section needs a bit of updating in terms of wording too.
I believe you are correct in the ratio
https://kirkmcdonald.github.io/calc.html#data=0-17-1&min=4&items=space-science-pack:r:150

**Comment by adrianvanderwal** [comment]
To be honest, I think it is *more* useful to have the second ratio shown.
You're talking about rockets - not space science.
