### ISSUE TITLE
Bad link in oil-refining section

### ISSUE THREAD

**Issue by DRY411S** [deniszholob/factorio-cheat-sheet#166]
The google sheets doc that you link to is one I produced and shared. It is valid for factorio 0.15 only.

I'm happy to update it for 0.16 and 0.17 and provide you with links, but in the interim could you note on the page that it's not correct for the current stable and experimental releases.

**Comment by deniszholob** [comment]
@DRY411S as the asterisk note says
`* Moduled cracking ratio is based on this spreadsheet from Reddit; assuming 5.55 craft speed for Refineries, 4.55 craft speed for Chemical Plants, and 1.3 productivity for both, and using 0.17 data.`
So i didn't just copy whatever values where there, i modified my inputs to align with 0.17, then cross-referenced with Kirks calculator. So the numbers should be accurate for the most part (rounding). Of course if there is a new spreadsheet available ill link it and re-run the numbers. Thanks!

**Comment by DRY411S** [comment]
I understand the distinction.

The sheet at the link is editable. People can insert their own numbers at the link. The results they get will not be aligned with your numbers on your site, and may mislead.

People may not notice the asterisked note. I didn't when I raised this issue. :)

**Comment by DRY411S** [comment]
In lieu of me providing new spreadsheets that are up to date for factorio 0.16 stable and 0.17 experimental, can I suggest the following update to oil-refining-component.html, to clarify the asterisked note. I don't have access to a linux machine at the moment to run your rebuild scripts, so cannot use your contributing.md method.

`<app-cheat-sheet [cheatSheet]="cheatSheet">
    <h4 id="basic-oil">Basic Oil</h4>

    <div class="row align-items-center">
        
        <p class="col-12 col-lg-7 text-center"> To research
            <app-factorio-icon [icon]="dataService.getFactorioIcon('Advanced_oil_processing')"></app-factorio-icon>
            <i class="fas fa-long-arrow-alt-right text-muted"></i>
            Need
            <app-factorio-icon [icon]="dataService.getFactorioIcon('Plastic_bar', sheetData?.rushAdvancedOil?.Plastic_bar)"></app-factorio-icon>
            using
            <app-factorio-icon [icon]="dataService.getFactorioIcon('Coal', sheetData?.rushAdvancedOil?.Coal)"></app-factorio-icon>
            to make
            <app-factorio-icon [icon]="dataService.getFactorioIcon('Chemical_science_pack', sheetData?.rushAdvancedOil?.Chemical_science_pack)"></app-factorio-icon>
            required.
        </p>
    </div>

    <p>
        When starting oil, it is most efficient to rush <a href="https://wiki.factorio.com/Advanced_oil_processing_(research)" target="_blank" rel="noopener">Advanced Oil Processing</a> research.
        <br>This allows to obtain more efficient oil ratios and be able to convert Heavy and Light Oil into Petroleum Gas,
        eliminating need to buffer or waste oil products.
    </p>

    

    <hr>
    <h4 id="advanced-oil">Advanced Oil</h4>

    <div class="row align-items-center">
        <p class="col-12 col-sm-6 text-center">
            <span class="text-muted">Accurate Cracking Ratio</span><br>
            <ng-container *ngFor="let item of sheetData?.perfectCrackingRatio">
                <app-factorio-icon [icon]="dataService.getFactorioIcon(item?.iconId, item?.count)"></app-factorio-icon>
            </ng-container>
        </p>

        <p class="col-12 col-sm-6 text-center">
            <span class="text-muted">
                <a href="https://www.reddit.com/r/factorio/comments/68exg4/new_oil_ratio_in_015_with_modules_10_2_14/">Moduled</a>
                Cracking Ratio<a href="#oil_ratio_note">*</a>
            </span><br>
            <ng-container *ngFor="let item of sheetData?.moduledCrackingRatio">
                <app-factorio-icon [icon]="dataService.getFactorioIcon(item?.iconId, item?.count)"></app-factorio-icon>
            </ng-container>
        </p>
    </div>

    <p>
        If you want to <a href="https://www.reddit.com/r/factorio/comments/67ipoj/015_cracking_ratio_25_refineries_3_heavy_to_light/" target="_blank" rel="noopener">convert all refinery products to petroleum</a>:
        for every {{sheetData?.perfectCrackingRatio[0]?.count}} refineries you have running Advanced Oil Processing,
        you need {{sheetData?.perfectCrackingRatio[1]?.count}} chemical plants cracking heavy oil into light oil and
        {{sheetData?.perfectCrackingRatio[2]?.count}} chemical plants cracking light oil into petroleum.
    </p>
    <p>
        This <a href="https://www.youtube.com/watch?v=wbscDTocZBk">Video</a>
        for 0.16 version that explains the calculations in detail.
        Ratios changed but the concept and build style are still relevant.
    </p>

    <div class="row align-items-center">
        <div class="col-12 col-lg-6 text-center col-print-6">
            <p class="text-muted">
                Water input for Refineries is after Oil going clockwise. <br>
                Water input for Chemical Plants is the opposite.
            </p>
            <div class="row align-items-center justify-content-around">
                <div class="col-6 col-sm-5 col-lg-6 text-center">
                    <span><strong>Refinery Plant IO</strong></span><br>
                    <img src="{{APP_SETTINGS.links.getLocalImagePath('fluid-io-refinery.gif')}}" class="img-fluid rounded"  alt="Refinery Plant IO" title="Refinery Plant IO">
                </div>
                <div class="col-6 col-sm-5 col-lg-6 text-center">
                    <span><strong>Chemical Plant IO</strong></span><br>
                    <img src="{{APP_SETTINGS.links.getLocalImagePath('fluid-io-chemical-plant.gif')}}" class="img-fluid rounded" alt="Chemical Plant IO" title="Chemical Plant IO">
                </div>
            </div>
        </div>

        <div class="col-12 col-lg-6 text-center col-print-6">
            <table class="table table-sm table-hover fixed-width">
                <caption class="text-center">Rates for 1 Refinery and Cracking</caption>
                <thead class="text-center">
                    <tr>
                        <th></th>
                        <th colspan="2">Liquids Needed</th>
                        <th colspan="3">Liquids Produced</th>
                    </tr>
                    <tr>
                        <th></th>
                        <th><app-factorio-icon [icon]="dataService.getFactorioIcon('Crude_oil')"></app-factorio-icon></th>
                        <th><app-factorio-icon [icon]="dataService.getFactorioIcon('Water')"></app-factorio-icon></th>
                        <th><app-factorio-icon [icon]="dataService.getFactorioIcon('Heavy_oil')"></app-factorio-icon></th>
                        <th><app-factorio-icon [icon]="dataService.getFactorioIcon('Light_oil')"></app-factorio-icon></th>
                        <th><app-factorio-icon [icon]="dataService.getFactorioIcon('Petroleum_gas')"></app-factorio-icon></th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    <tr *ngFor="let item of sheetData?.production">
                        <td>
                            <app-factorio-icon *ngFor="let process of item.processes" [icon]="dataService.getFactorioIcon(process?.iconId, process?.count)"></app-factorio-icon>
                        </td>
                        <td>{{item?.oil}}</td>
                        <td>{{item?.water}}</td>
                        <td>{{item?.heavyOil}}</td>
                        <td>{{item?.lighOil}}</td>
                        <td>{{item?.petrol}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <hr>
    <h4 id="coal-liquefaction">Coal Liquefaction</h4>

    <p>Ratios to convert everything into Petroleum Gas.</p>

    <div class="row align-items-center">
        <p class="col-12 col-sm-4 text-center">
            <span class="text-muted">
                <a href="https://wiki.factorio.com/Oil_processing#Petroleum_gas_production" target="_blank" rel="noopener">Simple</a>
                Cracking Ratio
            </span><br>
            <ng-container *ngFor="let item of sheetData?.simpleLiquefactionCrackingRatio">
                <app-factorio-icon [icon]="dataService.getFactorioIcon(item?.iconId, item?.count)"></app-factorio-icon>
            </ng-container>
        </p>

        <p class="col-12 col-sm-4 text-center">
            <span class="text-muted">
                <a href="https://wiki.factorio.com/Oil_processing#Petroleum_gas_production" target="_blank" rel="noopener">Accurate</a>
                Cracking Ratio
            </span><br>
            <ng-container *ngFor="let item of sheetData?.perfectLiquefactionCrackingRatio">
                <app-factorio-icon [icon]="dataService.getFactorioIcon(item?.iconId, item?.count)"></app-factorio-icon>
            </ng-container>
        </p>

        <p class="col-12 col-sm-4 text-center">
            <span class="text-muted">
                <a href="https://docs.google.com/spreadsheets/d/1Y6oL3Fl4P76_GAp6oNYDv9dXtjDKBE7xiUCtktTgFgY/" target="_blank" rel="noopener">Moduled</a>
                Cracking Ratio<a href="#oil_ratio_note">*</a>
            </span><br>
            <ng-container *ngFor="let item of sheetData?.moduledLiquefactionCrackingRatio">
                <app-factorio-icon [icon]="dataService.getFactorioIcon(item?.iconId, item?.count)"></app-factorio-icon>
            </ng-container>
        </p>
    </div>

    <hr>
    <h4 id="solid-fuel">
        <a href="https://wiki.factorio.com/Solid_fuel#Which_solid_fuel_recipe_to_use" target="_blank" rel="noopener">
            Solid Fuel
        </a> Production
    </h4>

    <p>Use light oil to produce the most amount of solid fuel per unit of crude oil.</p>

    <div class="row align-items-center">
        <div class="col-12 col-md-4 text-center">
            <span class="text-muted">Best</span><br>
            <span *ngFor="let item of sheetData?.solidFuel[0]; let idx = index">
                <i *ngIf="idx!=0" class="fas fa-long-arrow-alt-right text-muted" aria-hidden="true"></i>
                <app-factorio-icon [icon]="dataService.getFactorioIcon(item?.material, item?.count)"></app-factorio-icon>
            </span>
        </div>

        <div class="col-12 col-md-3 text-center">
            <span class="text-muted">OK</span><br>
            <span *ngFor="let item of sheetData?.solidFuel[1]; let idx = index">
                <i *ngIf="idx!=0" class="fas fa-long-arrow-alt-right text-muted" aria-hidden="true"></i>
                <app-factorio-icon [icon]="dataService.getFactorioIcon(item?.material, item?.count)"></app-factorio-icon>
            </span>
        </div>

        <div class="col-12 col-md-5 text-center">
            <span class="text-muted">Worst</span><br>
            <span *ngFor="let item of sheetData?.solidFuel[2]; let idx = index">
                <i *ngIf="idx!=0" class="fas fa-long-arrow-alt-right text-muted" aria-hidden="true"></i>
                <app-factorio-icon [icon]="dataService.getFactorioIcon(item?.material, item?.count)"></app-factorio-icon>
            </span>
        </div>
    </div>

    <hr>

    <p id="oil_ratio_note"><small>
        * Moduled cracking ratio is based on this
        <a href="https://docs.google.com/spreadsheets/d/1Y6oL3Fl4P76_GAp6oNYDv9dXtjDKBE7xiUCtktTgFgY/" target="_blank" rel="noopener">
            spreadsheet for factorio 0.15
        </a> from Reddit; The data presented here at factoriocheatsheet uses the same craft speeds as in the spreadsheet; 5.55 craft speed for Refineries,
        4.55 craft speed for Chemical Plants, 1.3 productivity for both, but has been modified for 0.17 recipe data. The spreadsheet will not produce correct results for version 0.17.
    </small></p>

</app-cheat-sheet>
`

**Comment by deniszholob** [comment]
I updated the note now and included my modified spreadsheet  that i copied from the Reddit link. Hope this avoids any further confusion.
