### ISSUE TITLE
Fix recipe for Flying Robot Frame

### ISSUE THREAD

**Issue by ungerrj** [deniszholob/factorio-cheat-sheet#169]
![image](https://user-images.githubusercontent.com/7469807/59133583-1c763f80-893e-11e9-9fe6-d05fe6667f31.png)

The current recipe (and ratios) shown for Flying Robot Frame in the Common Ratios section appears to just be wrong. I checked against 0.16 recipes, and it looks like it was the same then, so I'm not sure what the source of the displayed ratios is.

I will submit a pull request with what I believe are the correct ratios based on the current recipe in 0.17.

**Comment by deniszholob** [comment]
I think you misunderstood, this section does not list recipes, but rather ratios of various machines.
However, I updated the cheatcheet to link to the kirk's calculator results for each of the entries to be more clear. Thanks for the post though.
