### ISSUE TITLE
Oil recipes changed

### ISSUE THREAD

**Issue by deniszholob** [deniszholob/factorio-cheat-sheet#190]
Ref: https://factorio.com/blog/post/fff-304

* Basic Oil ref only produces petrol
* Basic Oil Ref produces 25% more petrol
* Basic Oil ref input/output visual change

**Comment by SquaredGrunt** [comment]
It's not implemented yet and may change depending on feedback.

**Comment by HonkingGoose** [comment]
Also see: https://factorio.com/blog/post/fff-305 for more information about the Oil Changes.

**Comment by HonkingGoose** [comment]
This is now implemented in 0.17.60: https://forums.factorio.com/viewtopic.php?f=3&t=73828

**Comment by deniszholob** [comment]
Data updated, closing
