### ISSUE TITLE
Sprites randomly permute when scrolling on iOS Safari 

### ISSUE THREAD

**Issue by shepmaster** [deniszholob/factorio-cheat-sheet#191]
https://imgur.com/a/yL0OlEq

Seems related to #66 

Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1

**Comment by deniszholob** [comment]
@shepmaster Is this still an issue, i dont have any ios devices to reproduce with

**Comment by HonkingGoose** [comment]
I cannot reproduce this bug on the current version of the website on my iPhone SE (2016).

**Comment by shepmaster** [comment]
I have not used the site in 6 months or so. A cursory check now doesn't immediately show the problem.
