### ISSUE TITLE
Change common ratios for Chemical Science (blue flask) after "Oil Recipe Change"

### ISSUE THREAD

**Issue by HonkingGoose** [deniszholob/factorio-cheat-sheet#192]
## What will probably change?

Chemical science will use **Sulfur** instead of Solid Fuel.

2x chemical science pack, 24 seconds to craft, requires:
- 1 Sulfur
- 3 Advanced circuit
- 2 Engine Unit

##Reference:
https://factorio.com/blog/post/fff-305
#190

**Comment by deniszholob** [comment]
Data updated, closing
