### ISSUE TITLE
Common Ratios Rocket Fuel after "Oil Recipe Change"

### ISSUE THREAD

**Issue by HonkingGoose** [deniszholob/factorio-cheat-sheet#193]
Rocket Fuel recipe will change sometime after [FFF#305](https://factorio.com/blog/post/fff-305)

> Rocket fuel behind chemical science pack, requires light oil.

Recipe will probably be:
1 rocket fuel, 30 seconds to craft, requires:
- 10 Solid fuel
- 10 Light oil

**Comment by deniszholob** [comment]
Looks like they added light to the recipe but crafting times remain the same so the common ratio should be fine.
![image](https://user-images.githubusercontent.com/3830741/65726614-7cc2f580-e083-11e9-968b-0457b8788854.png)
