### ISSUE TITLE
New Advanced Oil Cracking Accurate Ratio

### ISSUE THREAD

**Issue by unlimitedsola** [deniszholob/factorio-cheat-sheet#194]
Just did the calculation, the ratio is 20:5:17 now (without any modules). the result is 390 petroleum gas per second.

**Comment by Bilka2** [comment]
Spreadsheet that confirms the above: https://docs.google.com/spreadsheets/d/1UkKaRowYz0VZ0OoI-uYMEE6SSCfpNMnJU-04cE3JKK0/edit#gid=0

**Comment by deniszholob** [comment]
Data updated, closing
