### ISSUE TITLE
[Suggestion] Hamburger menu instead of arrow for navigation

### ISSUE THREAD

**Issue by AyeJayTwo** [deniszholob/factorio-cheat-sheet#196]
Most websites do a hamburger on the upper LHS to indicate navigation; the RHS arrow in the middle of the page is great but not an intuitive spot for users to see the option of skipping down to another section.

**Comment by deniszholob** [comment]
I was thinking of doing this but then im thinking maybe i should leave as is
Reason being its actually quite comfortable, esp when using the phone. The menu being in the center is a perfect distance away from your thumb to quickly bring up and go through different sheets without having to stretch all the way to top corners.
