### ISSUE TITLE
Mining section does not explain how electric mining drills work when placed on multiple ore deposits.

### ISSUE THREAD

**Issue by BrickVoid** [deniszholob/factorio-cheat-sheet#197]
If an Electric Mining Drill is placed on multiple ore deposits that are adjacent to each other, it will mine certain amounts of ore from each square for each deposit. I would like this issue changed to a suggestion to implement basic information on how electric mining drills handle mixed deposits.

The following should be added to the cheat sheet in some form or another, if not already present:

1. Belt Splitters - my game version has this capability and lists itself as version 0.16.51 - have filtering functions built into them. Advise users of designs that can help with filtering ore deposits and which are as compact as possible to save on space. Recommended for those users who feel they absolutely have to have all the ore from a deposit.

2. When it is preferable to have compact versus spaced Electric Mining Drills placed down on tiles containing mixed ore deposits. Sometimes Uranium Ore has other ores mixed in with it, this is one example where if playing on limited resource modes that players could benefit from information that allows mixed deposits to be handled properly.

3. When to consider if it's practical to use a mixed deposit containing coal and iron, copper, or stone resources.

4. General tips and tricks on how to best handle mixed metal ore patches for users who want to maximize what they can get out of a mixed deposit in a reasonable time frame.

**Comment by deniszholob** [comment]
I think this would be a full guide in itself, if you want to create one or find a good existing one, i could link it in the mining section. Also (3.4) Mixed ore patches dont seem to be very common with default settings and mostly are at the starting area wich gets mined out pretty quickly and usually is pretty unorganized anyways.
(2) I already have some mining configuration in an imgr link https://imgur.com/a/Imfhz 
(1) Also in the tips and tricks section there is a screenshot on filter splitter
