### ISSUE TITLE
HTTPS certificate is expired

### ISSUE THREAD

**Issue by dector** [deniszholob/factorio-cheat-sheet#201]
![Screenshot_2019-12-07_21-20-30](https://user-images.githubusercontent.com/265872/70378227-6fee3800-1937-11ea-816f-b2e5e2c192d6.png)

**Comment by deniszholob** [comment]
I think this may be resolved now?
![chrome_2019-12-15_11-13-29](https://user-images.githubusercontent.com/3830741/70865473-29e33680-1f2c-11ea-834e-727658a2ee81.png)
Closing
