### ISSUE TITLE
The most efficient nuke setup

### ISSUE THREAD

**Issue by DeeSee** [deniszholob/factorio-cheat-sheet#210]
![image](https://user-images.githubusercontent.com/397049/79148481-30949400-7dce-11ea-9d98-166a795b39ed.png)

If you shift one of the lines for two cells right or left, you'll still have access to all the reactors, but the reactors in the middle will have x5 modifier instead of x4

**Comment by Illiou** [comment]
Neighbor bonus is only applied if the reactors side flush side by side.

**Comment by DeeSee** [comment]
Oh, my bad then
