### ISSUE TITLE
All of Bilka's balancer links need an update.

### ISSUE THREAD

**Issue by williamtroy** [deniszholob/factorio-cheat-sheet#230]
All of the links to these balancers return a 404 error.

![image](https://user-images.githubusercontent.com/245013/83353314-568edd00-a317-11ea-81e4-0ff97bd8af4e.png)
![image](https://user-images.githubusercontent.com/245013/83353322-627a9f00-a317-11ea-95e3-e4b19e46e9e1.png)

**Comment by deniszholob** [comment]
Interesting, he seemed to have deleted them, i wonder why. I'll add them into this repo i guess, maybe they need updates?

**Comment by williamtroy** [comment]
Sweet baby Jesus, thank you so much. I've been looking for them all day long :'D

Thought they were lost forever!
