### ISSUE TITLE
Please credit blueprint creators correctly.

### ISSUE THREAD

**Issue by Bilka2** [deniszholob/factorio-cheat-sheet#232]
None of the blueprints linked as "Bilka's Balancers" are created by me. Please credit the actual creators and don't attach my name to things I didn't make. Thank you.

**Comment by deniszholob** [comment]
Hey @Bilka2!
Can you please clarify? These where on your gist b4 here https://gist.github.com/Bilka2/aeec4ff7123ff5544cb9a80cf1046a06
And yesterday i got a ticket #230 reporting all of them where causing 404 errors, i decided to just host the content myself instead of potential future outages.
These where the original links i was using
https://github.com/deniszholob/factorio-cheat-sheet/pull/231/files#diff-7018e529608d81c9cfc7f2918436990c
Looks like they still return a "404: Not Found"

**Comment by Bilka2** [comment]
My gist always tried to credit the authors, however it didn't do that fully. So I removed the blueprint books, that way I am not hosting content without giving proper credits.
Now, the gist directly credits all authors by linking to their work without introducing anything made by me.

By hosting the content yourself without giving any source for the blueprints, you are removing all credits to the original authors.

My suggestion for how to solve this would be to link the blueprint books directly provided by the authors (see imgur/reddit posts). That way you always credit the authors, because you are linking their work without modifying it.

**Comment by deniszholob** [comment]
I see,  I thought you created these, thanks for the clarification!
Ill look into how to update the balancer sheet to give proper credit, from a brief look, it seems like the are no separate 1-8 links as you had them before so ill have to modify the structure and presentation

**Comment by deniszholob** [comment]
Ive created a discussion post on Reddit to see what we can do about this
https://www.reddit.com/r/factorio/comments/gygv9y/help_update_factorio_cheat_sheet_balancer/

**Comment by Bilka2** [comment]
Looks good, thank you.
I have two more suggestions left:
* The title for the balancer image that you use directly in the sheet is "4 lane balancer", but that's a "4 belt balancer".
* You still have the [old blueprint strings](https://github.com/deniszholob/factorio-cheat-sheet/tree/master/src/assets/data/bilkas-balancers) here in the repo. They should probably be removed due to the crediting issue and they are also unused.
