### ISSUE TITLE
Add solar panel ratio details

### ISSUE THREAD

**Issue by chrisheib** [deniszholob/factorio-cheat-sheet#242]
I opened the cheat sheet to look for the 'total solar MW to usable solar MW' ratio, which is 1/1.43 = 0.699, so basically 0.7.
That means if I have solar panels worth 100 MW, i can only expect to get 70MW on average.
The other way around if I consume 100MW on average, I need a solar field providing 143MW peak power.

I couldn't find that ratio and needed to look it up in the wiki. 

Any ideas if/how to add it to the sheet?

**Comment by deniszholob** [comment]
There was mention of it before, but I made it more clear, good suggestion, thanks!
