### ISSUE TITLE
Update version to 1.0.0

### ISSUE THREAD

**Issue by HonkingGoose** [deniszholob/factorio-cheat-sheet#271]
Hi @deniszholob, I'll keep this change for you to make.
It's your repository, and a cool milestone for your project.
So I think you should make that change yourself.

Greetings,

HonkingGoose

p.s. I've opened some other pull-request to fix some small stuff.
Would you like me to continue fixing the other sections I haven't opened a pull for?

**Comment by deniszholob** [comment]
Done!
I updated the banner one again, I had to include Spidertron in there :p

Yeah, feel free, though if the same type of grammar type content fixes, if you could roll it all up in one PR it would be easier to merge, thankssss! :D

**Comment by HonkingGoose** [comment]
Yeah Spidertron is really cool! It will take some researching to get on my new play-trough though. 🕷️

>Yeah, feel free, though if the same type of grammar type content fixes, if you could roll it all up in one PR it would be easier to merge, thankssss! :D

Here's the one PR to rule them all: #273
