### ISSUE TITLE
Change common ratio's display

### ISSUE THREAD

**Issue by deniszholob** [deniszholob/factorio-cheat-sheet#283]
Seems there is confusion about the common ratio presentation
Try too change to be more like the https://deniszholob.github.io/satisfactory-cheat-sheet/

* Common Ratio Sheet
* Science Sheet
* Oil Sheet

**Comment by DRY411S** [comment]
Perhaps when this enhancement is made you should add the assembler for radars (and satellite?) to the space science maker? You have all the other ingredients (solar, accumulators, blue chips) but not radar.

**Comment by deniszholob** [comment]
@DRY411S the common ratio for Space science includes materials for satellite, if you click on that ratio and look at kirks calculator table that it sends you to, you can see radars are only but 0.1 assemblers, not worth including in the ratios as most would have a MEF/MALL to produce those anyways.
