### ISSUE TITLE
[Suggestion] Remove tip to "rush" Advanced Oil Processing from the Oil Refining section

### ISSUE THREAD

**Issue by jgargus** [deniszholob/factorio-cheat-sheet#285]
Since the change to Basic Oil Processing to only produce petroleum, there is no longer a need to rush Advanced Oil Processing. Having this "tip" as the first advice to new players in the Oil Processing section is very misleading.

New players should focus on setting up plastic and sulfur production only, to enable chemical science production. They can safely ignore light/heavy oil production and cracking until they need to produce lubricant or rocket fuel in significant quantities.

**Comment by deniszholob** [comment]
@jgargus I still think rushing adv oil processing is the right way to go as not only, "This unlocks Light/Heavy Oil, and enables more efficient oil processes by converting the Light and Heavy Oil into Petroleum Gas." so you get more petrol for the money so to speak, but also unlocks the road to robots via lube which are an invaluable tool post oil gameplay.

"New players should focus on setting up plastic and sulfur production only, to enable chemical science production. " yes, that is a prerequisite for Advanced Oil Processing in the first place!

**Comment by deniszholob** [comment]
Closing for now, can reopen later if there is another way to word things :)
