### ISSUE TITLE
Incorrect amount of U-238 for a fuel cell on the picture

### ISSUE THREAD

**Issue by artyomsafronov** [deniszholob/factorio-cheat-sheet#286]
![fuel_cell_u238_amount_issue](https://user-images.githubusercontent.com/3224608/94994159-8d635100-059e-11eb-923d-2f022aab34cd.jpg)

**Comment by deniszholob** [comment]
@artyomsafronov actually this is correct, if you read the complete sentence till the very end:
"It takes 1 U-235 and 19 U-238 to create 10 fuel cells, but you can reprocess 10 used up uranium fuel cells to get 6 U-238, which results in a ratio of 13 U-238 to 1 U-235."
