### ISSUE TITLE
Pipe Throughtput

### ISSUE THREAD

**Issue by Mattia2510MC** [deniszholob/factorio-cheat-sheet#299]
Consider adding something like this: [Pipelines](https://wiki.factorio.com/Fluid_system#Pipelines)

**Comment by deniszholob** [comment]
Its mentioned in the https://factoriocheatsheet.com/#fluid-wagon-transfer section
There is a graph on pipe flow as well

**Comment by deniszholob** [comment]
Closing, reopen if needed
