### ISSUE TITLE
Where did the Combat section go?

### ISSUE THREAD

**Issue by DRY411S** [deniszholob/factorio-cheat-sheet#300]
^this

Used to be just below 'Common Ratios' before they were moved higher up the contents.

I can see that removal is referenced in #187, but not explicitly referenced in the discussion for removal. Personally I think the ranges of weapons and enemies were never better epresented than in the graphic that used to be in the cheat sheet. Certainly there's nothing like it that I can find in the wiki.

**Comment by deniszholob** [comment]
It moved under the Tips Sheet in the Misc section

**Comment by DRY411S** [comment]
Thank you, I obviously did not look hard enough.
