### ISSUE TITLE
Modules and Beacons Formula Needs More Context

### ISSUE THREAD

**Issue by vernon-v** [deniszholob/factorio-cheat-sheet#302]
In it's current form, the formula in the Modules and Beacons section can provide incorrect results.  It's current context is to determine the number of machine needed to consume a certain rate of ingredients.  The formula is correct only when the Machine Productivity value is 1.  Changing the machine's productivity, should only alter the output rate, not affect it's input rate.  It would affect crafting speed, but you are already accounting for that in Machine Craft Speed.

For example, with the simple values of:
 Item Consumption Rate: 45
 Recipe Base Craft Time: 1
 Items per Craft: 1
 Machine Craft Speed: 1
 Machine Productivity: 1

The calculated value is 45 machines needed.  That makes sense, each machine uses 1 item per second and the source is providing at 45 items per second, you need 45 machines to keep up.

But if you change the Machine Productivity to 2, the calculated value is 22.5.  This doesn't make sense as each machine still consumes 1 item per second.  The productivity in this context only changes output rate, it would produce twice as many items.  You still need 45 machines to consume the 45 items per second.

**Comment by deniszholob** [comment]
Thanks; "Consumption" here was misleading, it was referring to consuming the output, ie the Production Rate of the machine.
Changing the wording...
