### ISSUE TITLE
Add a dynamic calculator to solar power section

### ISSUE THREAD

**Issue by rattrapper** [deniszholob/factorio-cheat-sheet#305]
Add a calculator to tell number of solar panels and accumulators needed for desired power output. Maybe something similar to labs calculator 
![image](https://user-images.githubusercontent.com/11691295/113577262-a6ba8800-9629-11eb-85e8-6ed8b133c910.png)

**Comment by deniszholob** [comment]
Probably not like this as it doesnt need to be that detailed i think, but maybe more like the nuclear one.
But not a table i think, also include steam too since they are in the same section
