### ISSUE TITLE
The weapon range comparison diagram infographic is out of date

### ISSUE THREAD

**Issue by DRY411S** [deniszholob/factorio-cheat-sheet#306]
Appreciate it's not your graphic, but it is out of date. Maybe some notes on the page to that effect?

https://imgur.com/6EenAcn

**Comment by deniszholob** [comment]
Any specifics that are wrong?
Or is it just incomplete (no spidertron for example)?
If there isnt any wrong info, i think it should still be fine, but we can leave this issue open in case some1 wants to contribute a better image

**Comment by DRY411S** [comment]
> Any specifics that are wrong?
> Or is it just incomplete (no spidertron for example)?

The ranges of some of the weapons have changed. It's possible looking at factorio changelog that the infographic was NEVER correct. Examples:

Turret is 18 not 17 https://wiki.factorio.com/Gun_turret
Rockets are 36 not 43 https://wiki.factorio.com/Rocket_launcher
2 of the 4 spitters are wrong (should be 13,14,15,16) https://wiki.factorio.com/Enemies#Spitters

Many in the infographic are 1 different than the wiki, which may be a way the graphic 'counts', but the rocket launcher is the one that is most significantly 'wrong'.
