### ISSUE TITLE
Actual cheats

### ISSUE THREAD

**Issue by DeadlyDad** [deniszholob/factorio-cheat-sheet#322]
Personally, I find it amusing that a 'cheatsheet' doesn't include actual cheats, which is a shame.  

I use creative mode to make my blueprints for my main games and having infinite chests/etc. handy is _really_ important for that.  Unfortunately, I have to spend time searching the internet to remind myself how to add them to my inventory.  It would be a great addition to the cheatsheet to have a section dedicated to letting players know how to spawn items at will, including a link to [the official item name list](https://wiki.factorio.com/Data.raw), and _specifically_ mentioning the infinite items entities: `infinity-chest`, `infinity-pipe`, and `electric-energy-interface`.

Telling players how to use the info is necessary.  (e.g. typing '`/c game.player.insert{ name="infinity-chest", count=10 }`' in the console.)

Does that make sense?

**Comment by deniszholob** [comment]
> Personally, I find it amusing that a 'cheatsheet' doesn't include actual cheats, which is a shame.

Haha, weeeell is more of a reference than a list of "cheats" :p https://en.wikipedia.org/wiki/Cheat_sheet and really more of a sheet sheet collection since each "section" is a "cheat sheet" in itself.. but i digress...

> It would be a great addition to the cheat sheet to have a section dedicated to letting players know how to spawn items at will

I can probably throw this into the https://factoriocheatsheet.com/#tips section

**Comment by deniszholob** [comment]
The commands sections is a link to the wiki that has a good list of scripting snippets and a full list of single/multi player commands, including inserting items. Thus will not be implementing this
![image](https://user-images.githubusercontent.com/3830741/166318722-170b5be9-b376-46ca-881f-ed330fb94bfe.png)
