### ISSUE TITLE
New balancer book (Spring 2022)

### ISSUE THREAD

**Issue by blyzzz** [deniszholob/factorio-cheat-sheet#332]
https://www.reddit.com/r/factorio/comments/u7zv6d/balancer_book_update_spring_2022/

**Comment by deniszholob** [comment]
My link already points to the latest master branch here
https://github.com/raynquist/balancer/blob/master/blueprints/balancer_book.txt
https://github.com/deniszholob/factorio-cheat-sheet/blob/1649a1395ce4b35ad140bdc6448cd04947c0f7cc/src/app/views/cheat-sheets/balancers/balancers.component.html#L52
