### ISSUE TITLE
[TRIVIAL] Misleading text in the Lab calculator section

### ISSUE THREAD

**Issue by DRY411S** [deniszholob/factorio-cheat-sheet#334]
At https://factoriocheatsheet.com/#science there is the text

"Numbers assume a 12 beacon setup, which is researching a 60 second infinite tech."

This isn't true for 2 reasons

1. The calculator requires me to enter the lab speed bonus which is described on the page as "Speed bonus as reported by the lab, including modules and beacons." Therefore the number of beacons is taken care of there, the calculation does NOT assume 12 beacons, it is based on the lab speed bonus input field.
2. The calculator also allows me the change the cycle time from 60 seconds, so it's not based on a fixed 60 second infinite tech cycle.

I propose that the text is changed to be

"The calculator assumes that the lab speed bonus entered is identical for every lab."

**Comment by deniszholob** [comment]
I think that comment is referring to the default values, so i think i would rather change it to 
`Default numbers assume a 12 beacon setup, which is researching a 60 second infinite tech.`
