### ISSUE TITLE
Incorrect simple build nuclear ratios 

### ISSUE THREAD

**Issue by frumpy3** [deniszholob/factorio-cheat-sheet#335]
Simple build nuclear ratios are incorrect.
It’s stated that you’re rounding up the count of turbines and water pumps, but if this was the case then the 4 core should list: 4 reactor: 5 water pump: 48 exchanger: 83 turbine. As it is right now it says 4 water pump (not enough liquid) and it says 84 turbine (1 too many for full throughput 4 core). The 1 fluid pump : 12 exchanger ratio below this is also wrong, 1 fluid pump feeds only 11.65 exchangers.

relevant maths: (480 / 5.82) = 82.47 turbines,

using 82.47 * 60 = 4,948 fluid per second. 4 water pumps is 4,800. Similarly heat exchangers use more than 100 fluid per second, they use 103.093 fluid per second, so using 12 per water pump would not be correct.

**Comment by deniszholob** [comment]
> It’s stated that you’re rounding up the count of turbines and water pumps, but if this was the case then the 4 core should list: > 4 reactor: 5 water pump: 48 exchanger: 83 turbine. 
I agree that they are incorrect in terms of exactness, but as you pointed out, i am stating that i am rounding the numbers to make a "pretty"/evenly divisible ratio that is easier to build than an exact one.
Ex: 4:4:48:84 evenly simplifies to 1:1:12:21 for clean x/y mirrored symmetry in a blueprint, also its very ez to keep tack of as there are 2 unique numbers in that ratio 4 and 8

> The 1 fluid pump : 12 exchanger ratio below this is also wrong, 1 fluid pump feeds only 11.65 exchangers.
I agree that this is not exact but again, thus the note about rounding. Its easier to work with 1:12 than 11.65 practically as in, you cant build 11.65 HEs
Again, that section is for some quick EZ estimated "practical" ratios too give a quick idea of what to build, and i provide the table below that is actually exact to the decimal points if you uncheck the 'Round Up" box.

Thanks for your contribution :), but i don't think ill be changing this, i hope my explanation makes sense.
Perhaps my note isnt clear enough? Maybe i can tweak that wording a bit to better get my intention across?
