### ISSUE TITLE
Productivity modules payoffs are based on wrong calculations

### ISSUE THREAD

**Issue by iniju** [deniszholob/factorio-cheat-sheet#345]
The numbers there are based onn https://docs.google.com/spreadsheets/d/1M3bbVKSs3IWzLtBHEbe0iJcbnh7raERDcL6dOh1y3oY/edit#gid=1732247322
but that spreadsheet has a big error.

If you make copy of the spreadsheet and unhide columns AC to AJ, you will see that the cost of the prod-module-3 is incorrectly set to be the same as the cost of prod-module-1 (probably a copy-paste error of the formula). The correct cost is more like 3800+, not 62.5.

Another smaller error I noticed is the cost of blue-chip (also used in calculating prod-modules costs), which is set to 70.85, while I think 76.85 is the correct value.

**Comment by deniszholob** [comment]
@iniju, thanks for the report.
This is what i see:
![image](https://user-images.githubusercontent.com/3830741/207718830-a3b1c681-25d4-4b51-86d1-047f9c8fefb9.png)
Tier 1 | Tier 2 | Tier 3
-- | -- | --
62.5 | 654.25 | 3675.5

Tier 3 is definitely not the same as tier1
Or are you referencing something else?

As far as the blue chip cost, im actually not quite familiar with the formulas, do you know where this number is coming from?

**Comment by iniju** [comment]
Thanks for the reply, your spreadsheet looks correct then, maybe it was corrected since yesterday, or maybe I was looking at an old version of the spreadsheet.

I was wrong about the blue chip cost. I redid my calculations and 70.85 is correct. You can close this issue.

For reference, for the costs, all minerals count as 1 and all oil liquids as 0.1, water is free.
You can actually see how each cost is calculated in the spreadsheet, in the columns R and S.

The cost for blue chip is 2 reds, 20 green 5 acid.
1 green costs 3 copper cable + 1 iron plate = 1.5 copper plate + 1 iron plate = 1.5 copper ore + 1 iron ore = 2.5
1 red costs 4 cable + 2 green + 2 plastic = 2 copper plate + 2 green + 2 plastic
2 plastic costs 1 coal + 20 pet gas = 1 + 2 = 3
So red costs 2 + 2*2.5 + 3 = 10

50 acid = 1 iron plate + 5 sulfur
2 sulfur = 30 pet gas + water => 1 sulfur costs 1.5
So 50 acid costs 1+5*1.5= 8.5 or 5 acid costs 0.85
So back to the blue chip, costs 20 * green + 2 *reds + 5*acid = 20*2.5 + 2 * 10 + 0.85 = 70.85

**Comment by deniszholob** [comment]
Thanks! I updated the cheat sheet to include part of your explanation then link it here
