### ISSUE TITLE
"Miners needed to fill a belt" calculator seems to be broken

### ISSUE THREAD

**Issue by Equbuxu** [deniszholob/factorio-cheat-sheet#352]
Changing mining productivity level doesn't change the table in any way, and the supposedly calculated productivity percentage also stays at 10%. What's interesting is that the table does get regenerated (you can see it flicker with devtools opened) yet the values stay the same.

Using chrome 108.0.5359.125

**Comment by deniszholob** [comment]
Thanks!
Good catch, silly regression error... :/
