### ISSUE TITLE
Add info on miners/centrifuges for Nuclear 

### ISSUE THREAD

**Issue by Dimava** [deniszholob/factorio-cheat-sheet#377]
People often overestimate Uranium consumption 

While actual amount of Uranium used is just 12 miners and 6 centrifuges for 480MW reactor, or whatever

Please add this to cheatsheet to prove Solar peoples Nuclear is good

**Comment by deniszholob** [comment]
Update the summary section with drills and chem plants and linked to calculator
![image](https://user-images.githubusercontent.com/3830741/212764435-5f275e5f-50c8-40e7-b2a7-5e7f7c3e1459.png)
