### ISSUE TITLE
Typo in fluid wagon Transfer section

### ISSUE THREAD

**Issue by LostIntelligence** [deniszholob/factorio-cheat-sheet#405]
With 2.0 / Space Age the Capacity of fluid wagons was increased, to 50k from 25k however the text in the fluid wagon transfer section doesn't fully reflect that: (Fluid wagons can hold 25,000 units of fluids which is equal to 2 Storage Tanks.). It says 2 Tanks but gives the wrong number: 25,000 units instead of 50,000 units

**Comment by deniszholob** [comment]
good catch thanks!
