### ISSUE TITLE
Mining section doesn't account for productivity bonuses

### ISSUE THREAD

**Issue by gotube** [deniszholob/factorio-cheat-sheet#50]
It would be nice to have a way to adjust the numbers of miners required to fill a belt based on that bonus. From just the green science phase, the game gives access to productivity bonuses on miners, and from then on, the numbers aren't accurate, so it's no longer useful as a quick reference.

Thanks again!

**Comment by DDDGamer** [comment]
Hmm interesting, good idea, ill think about it more.
Thanks!

**Comment by DRY411S** [comment]
Maybe merge this enhancement with #79 ?

**Comment by HonkingGoose** [comment]
**Mining productivity** is rebalanced from 0.17.5 onwards:
>Changed mining productivity technology to add 10% in one level instead of 2%, increased the formula from 100 * level to 500 * level and removed some of the low level intermediate levels.

**Comment by Meow-Mixer** [comment]
I would be good to mention that productivity modules are additive with the research, not multiplicative.

**Comment by s3bash** [comment]
Would need to setup the mining section to be calculated from base values with regards to a user choose-able productivity bonus instead of the static values they are now. Could cheat and just divide the number of miners required by the prod bonus.

**Comment by deniszholob** [comment]
I think this auto closed, gunna reopen as I still want to explore adding some calculations to the table.

**Comment by deniszholob** [comment]
#222 Fixes this, idk why i put 10 instead of 50 there...
