### ISSUE TITLE
Uranium Facts

### ISSUE THREAD

**Issue by ndrsbhm** [deniszholob/factorio-cheat-sheet#53]
The icon shows 10,000 x uranium ore -> 7 x uranium-235, 993 x uranium-238.
Shouldn't this be 1000 x uranium ore?

**Comment by DDDGamer** [comment]
No because you use 10 ore (not 1) and 99.3% chance to produce 1 uranium-238 and a 0.7% chance to produce 1 uranium-235 from 10 ore.
So its a 10:1 ratio not 1:1

**Comment by deniszholob** [comment]
Need to add a reference/explanation, as there are a number of people still thinking this is an error.
