### ISSUE TITLE
Printable or electronic version of this cheat sheet

### ISSUE THREAD

**Issue by Rapt0r22** [deniszholob/factorio-cheat-sheet#67]
As in title.

**Comment by DDDGamer** [comment]
What do you mean by electronic version?
Not sure what you mean by printable as well, could you not print from the browser?

**Comment by Rapt0r22** [comment]
By electronic (also as well as printable), what sohuld i mention first) i mean PDF, DOC or ODT file. There is a problem with "Print to PDF". Some of the tables (also standard text) are out of paper, menu button appears and overlaps small part of every page.

**Comment by DDDGamer** [comment]
Hmm, interesting use-case, ill take a look see what i can do. Preliminary research points to an additional print stylesheet.

**Comment by deniszholob** [comment]
This link looks great https://www.jotform.com/blog/css-perfect-print-stylesheet-98272/
Thanks for the info!

**Comment by deniszholob** [comment]
Added print styles
Printed sheet looks good for me in Firefox, but Chrome is not recognizing my page-break rules, not sure how to resolve that.
I added a download link to a pdf, that I generated using the print function in FF, in the Overview section for convenience.
