### ISSUE TITLE
New stack sheet?

### ISSUE THREAD

**Issue by deniszholob** [deniszholob/factorio-cheat-sheet#69]
Add another cheat sheet with stack related things

* Stack table for all items: https://wiki.factorio.com/Stack
* Train cargo wagon stacks: 4 rows of 10 = 40
* Steel, iron wood chests
* Stacks per chest for cargo wagon

**Comment by Mikrotherion** [comment]
OK... here come the screenshots:
![cheatsheet2](https://user-images.githubusercontent.com/26279012/47434478-efa45c00-d7a2-11e8-89d0-cadb2406f57a.png)
![cheatsheet1](https://user-images.githubusercontent.com/26279012/47434479-efa45c00-d7a2-11e8-8cce-1c6c9058252b.png)

**Comment by deniszholob** [comment]
I think stack table is too long/impractical to put this in, I already put a chest table into the Cargo Wagon. If this information can be condensed maybe we can reconsider
I'll reopen if needed. Some work has been done in #77
