### ISSUE TITLE
Add section for turret DPS and enemy health

### ISSUE THREAD

**Issue by itchylol742** [deniszholob/factorio-cheat-sheet#81]
Example image (data values are made up):
![image](https://user-images.githubusercontent.com/42976312/48595539-10d01680-e923-11e8-948b-ffb398bba6dc.png)
The example only shows laser turrets because it would be simpler to calculate - only have to take into account rate of fire research and damage research. Gun turrets have rate of fire, gun turret damage, bullet damage, and ammo used, which would probably involve a drop down menu to select at least 2 of those variables to set.

**Comment by deniszholob** [comment]
How useful is this though?
* You can view all the modifiers in game including damage.
* Not many enemies to keep track of, hp doesn't really matter right , because of evolution buffs?
* 0.17 will change some combat mechanics, lets discuss this after that comes out if still relevant?

**Comment by tzwaan** [comment]
A possibly more useful overview would be the amount of biters (of each kind) killed per amount of ammo. Scaled with the damage modifiers and the like.

That's actually a not-so-easily acccessible number in the game.

**Comment by deniszholob** [comment]
Just nuke 'em all :p But yeah, i like that better. Or how fast/how many shots it takes to kill 1 maybe

**Comment by itchylol742** [comment]
How about something like this: (data also made up, but you get the point)
![image](https://user-images.githubusercontent.com/42976312/48665844-c7e3a380-ea83-11e8-817c-acc78eec9e97.png)
It has damage and fire rate on the same axis because I assume people would upgrade both, instead of maxing out one then the other.

**Comment by tzwaan** [comment]
I don't find that as useful as the amount of ammo though. Or the amount of power used. Knowing how many accumulators of power you need for a certain wave of biters is much more useful than the time it actually takes to kill them.

**Comment by deniszholob** [comment]
Agreed, ammo usage is more quantifiable.
Im thinking a comparison to how many rounds/shots of different kinds it takes to kill a certain enemy.

|Ammo|Small Biter|Small Spitter|
|---|---|---|
|Yellow|100|50|
|Red|50|25|
|Uranium|10|5|
|Nuke|1|1|

**Comment by deniszholob** [comment]
I dont know if this is really all that useful in the end, i think im gunna close, if there are any new ideas we can re-open
