### ISSUE TITLE
Update with HQ Screenshots

### ISSUE THREAD

**Issue by deniszholob** [deniszholob/factorio-cheat-sheet#85]
* Need to update all the screenshots with the new High res/redone graphics.
* Run through https://tinyjpg.com/ to optimize
* Add Belt weaving screenshot to tips

**Comment by HonkingGoose** [comment]
Title issue spelling error: Screnshots should be: Scr**e**enshots

**Comment by deniszholob** [comment]
All done now except the Fluid Wagon Transfer ones to keep consistent with the GIF. May reopen later for v1 or something.
