### ISSUE TITLE
Update science pack names for 0.17

### ISSUE THREAD

**Issue by HonkingGoose** [deniszholob/factorio-cheat-sheet#92]
The science pack names are used in the "hover-over" text for the icons for the flasks/packs. There might be other instances where the names are used too.

**Red**: Automation science pack.
**Green**: Logistic science pack.
**Grey**: Military science pack.
**Blue**: Chemical science pack.
**Purple**: Production science pack.
**Yellow**: Utility science pack.
**White**: Space science pack.

Source: https://www.factorio.com/blog/post/fff-275

For reference, straight from FFF#275:

![](https://cdn.factorio.com/assets/img/blog/fff-275-04-new-science-packs.png)

**Comment by HonkingGoose** [comment]
For reference, straight from FFF#275:
![image](https://user-images.githubusercontent.com/34918129/50524216-cd95c580-0ad4-11e9-841d-784b161ed601.png)

**Comment by deniszholob** [comment]
This should have been taken care of by the id issue #120 with PR #126
