### ISSUE TITLE
Update Low density structure for 0.17

### ISSUE THREAD

**Issue by HonkingGoose** [deniszholob/factorio-cheat-sheet#94]
From FFF275:
>The Space science pack is only influenced by **Low density structures having a slightly different recipe (20x copper plate, 2x steel plate, 5x plastic bar)**, but other than that it is the same. 

Source: https://www.factorio.com/blog/post/fff-275

This recipe change will probably also affect the Productivity module payoff for the low density structure.

**Comment by deniszholob** [comment]
Nothing to do here really

**Comment by deniszholob** [comment]
Never mind...
Low Density structure is now a 20 second craft, yet its stated that " As these components all have the same crafting time, this ratio applies. "

**Comment by deniszholob** [comment]
Taken care of now.
