### ISSUE TITLE
Update productivity Module Payoffs for 0.17

### ISSUE THREAD

**Issue by HonkingGoose** [deniszholob/factorio-cheat-sheet#95]
The productivity module payoff will probably change with:
- The change of some science pack recipes both in number of packs per craft and crafting time. 
- The Low density structure recipe change.

I'm assuming that the grand picture probably won't shift drastically in that the rocket, labs and yellow and purple packs will stay good picks for first production modules. But the list will need updating to be more accurate.

Source: https://www.factorio.com/blog/post/fff-275

**Comment by HonkingGoose** [comment]
Hi @deniszholob you can see that I opened a lot of new issues for version 0.17 of your Factorio Cheat Sheet.

I hope you find the new issues for 0.17 helpful. There are a lot of changes planned for 0.17, I hope I got all of them for you. I thought you might like some help in getting those changes lined up for your v.017 milestone on Github.

If you find any issue not to your liking or annoying, feel free to edit/close them as you wish. It is after all your issue tracker. :smile: :+1:

**Comment by deniszholob** [comment]
Got in contact with MadZuri, he said he will notify me when he updates the payoffs.

**Comment by deniszholob** [comment]
New module payoffs sheet by MadZuri
https://docs.google.com/spreadsheets/d/1M3bbVKSs3IWzLtBHEbe0iJcbnh7raERDcL6dOh1y3oY/
