### ISSUE TITLE
Update Belt Troughput for 0.17

### ISSUE THREAD

**Issue by HonkingGoose** [deniszholob/factorio-cheat-sheet#96]
Relevant quote from Friday Facts #276:
>The change overall gives a 12.5% buff to belts, provides nice round integers for calculating factory requirements, and removes a few oddities. 

Yellow Belt will be 15 i/s for both sides.
Red Belt will be 30 i/s for both sides.
Blue Belt will be 45 i/s for both sides.

**Source**: https://factorio.com/blog/post/fff-276

**Comment by deniszholob** [comment]
The image caption also would need updating (possibly image too? would it read 8 still?)

**Comment by HonkingGoose** [comment]
@deniszholob I can't assign this issue to myself. I don't see the checkbox mentioned at step 3 of the help page. It's probably because I'm not in the collaborator section of your repository?

https://help.github.com/en/articles/assigning-issues-and-pull-requests-to-other-github-users

**Comment by deniszholob** [comment]
I assigned you to it, i guess, just comment on an issue if you want to take it :)
If you want you can update the collaborator.md file to say that as well in this PR

**Comment by HonkingGoose** [comment]
I'll just comment on a issue if I want to take it. :)
