### ISSUE TITLE
Update Material Processing for 0.17

### ISSUE THREAD

**Issue by HonkingGoose** [deniszholob/factorio-cheat-sheet#97]
Because of belt speed changes, it's likely that the furnace count needed to smelt a fully compressed belt is going to change too. Unless of course, the furnace recipes are going to be changed too. The nuclear processing section will likely also change.

From the Factorio forum from developer V453000,  there is already a proposal for a smelting recipe change:
> As the smelting recipe change, I am proposing the following:
>- Iron plate, copper plate, stone brick: 3.2
>- Steel: 16

>That would mean exactly 48 stone furnaces per yellow belt, which is the number that people already build, but some of the last ones flicker with inactivity in 0.16, now all of them would work nonstop.

Source for furnace recipe change proposal: https://forums.factorio.com/viewtopic.php?t=64219#p392508

**Comment by deniszholob** [comment]
From https://factorio.com/blog/post/fff-276
"A next step we are considering is tweaking the furnace recipes to match the belt speed, but that is a consideration for another day."

So we shall see if ratios change

**Comment by HonkingGoose** [comment]
We'll have to wait and see then if the ratios change, at least it's on your milestone so you know to check that part when 0.17 comes out.
